In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
import numpy as np
import pandas as pd
from src.features import add_rfm_features

In [3]:
# import dataset
df = pd.read_csv(f'D:\\retail-projects\\online-retail-analysis\\data\\processed\\online_retail_cleaned.csv')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year,Month,Day,Revenue,Weekday
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009,2009-12,1,83.4,1
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009,2009-12,1,81.0,1
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009,2009-12,1,81.0,1
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009,2009-12,1,100.8,1
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009,2009-12,1,30.0,1

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1026994 entries, 0 to 1026993
Data columns (total 13 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1026994 non-null  str
 1   StockCode    1026994 non-null  str
 2   Description  1026994 non-null  str
 3   Quantity     1026994 non-null  int64
 4   InvoiceDate  1026994 non-null  str
 5   Price        1026994 non-null  float64
 6   Customer ID  797807 non-null   float64
 7   Country      1026994 non-null  str
 8   Year         1026994 non-null  int64
 9   Month        1026994 non-null  str
 10  Day          1026994 non-null  int64
 11  Revenue      1026994 non-null  float64
 12  Weekday      1026994 non-null  int64
dtypes: float64(3), int64(4), str(6)
memory usage: 101.9 MB

In [5]:
# drop nan
df.dropna(inplace=True)

### Extract RFM features:

R (Recency) → How recently they bought
         “Are they still active?”

F (Frequency) → How often they buy
         “Are they loyal?”

M (Monetary) → How much they spend
         “Are they high value?”

In [6]:
df = df.copy()

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["Customer ID"] = df["Customer ID"].astype("Int64")  # keeps NaNs safely

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 797807 entries, 0 to 1026993
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      797807 non-null  str
 1   StockCode    797807 non-null  str
 2   Description  797807 non-null  str
 3   Quantity     797807 non-null  int64
 4   InvoiceDate  797807 non-null  datetime64[us]
 5   Price        797807 non-null  float64
 6   Customer ID  797807 non-null  Int64
 7   Country      797807 non-null  str
 8   Year         797807 non-null  int64
 9   Month        797807 non-null  str
 10  Day          797807 non-null  int64
 11  Revenue      797807 non-null  float64
 12  Weekday      797807 non-null  int64
dtypes: Int64(1), datetime64[us](1), float64(2), int64(4), str(5)
memory usage: 86.0 MB

In [8]:
# RFM = how valuable a customer is based on behavior:
rfm = add_rfm_features(df)
rfm.head()

   Customer ID  Recency  Frequency  Monetary
0        12346      325         17    -51.74
1        12347        1          8   4921.53
2        12348       74          5   2019.40
3        12349       18          5   4404.54
4        12350      309          1    334.40